### ISSUE TITLE
process_data() documentation, an OMRON script

### ISSUE THREAD

**Issue by chasbecker** [johnschwenck/bp#5]
I finally figured out what I needed to do to preprocess a data table from my OMRON blood pressure cuff for the process_data() function.  It worked, but would have been quicker with concise documentation by output field of the expected input.  Eg; 'required', 'optional', and 'calculated'.  Maybe I missed it, but a table would be very nice.

Here's a link to the preprocessor script I ended up with, in case someone else is wrangling OMRON data: https://github.com/chasbecker/bp/blob/main/main.R

**Comment by johnschwenck** [comment]
Hi Charles,

I am not entirely sure I understand what you mean by a table of the output field for the expected input. Are you referring to which arguments in the process_data are required / optional / calculated? If so, the documentation available on CRAN [found here](https://cran.r-project.org/web/packages/bp/bp.pdf) states explicitly whether or not a given function argument is optional or required (only SBP & DBP are required for HBPM or ABPM data FYI). However, this is a good suggestion for the readme which I will adjust accordingly on GitHub.

My second question is regarding the OMRON data. Is your data file specific to OMRON (such as .omron for example), or does it just produce a .CSV file? If it outputs a CSV file, would you mind sending me a sample file so that I can see how it is structured? This will allow me to make sure that the process_data function will comply with that specific format. 

Best,
John Schwenck

**Comment by chasbecker** [comment]
Hello John,

Sorry about the delayed response.  It seems that OMRON changed the names of two of the columns in their data file output, so I had to tweak my preprocessor code.  I've uploaded an OMRON format data file here: https://github.com/chasbecker/bp/tree/main/Data  I recommend opening in a text editor rather than MS Excel because Excel does some reformatting of its own.

Yes, the docs do provide enough info to figure out which fields to provide and which are calculated.  I just thought that some sort of graphical matrix-type thing would ease the task.

**Comment by johnschwenck** [comment]
Thanks for bringing this to light. I don't necessarily think this is an issue, but rather more of a specific format from OMRON data that is to be processed in a specific way. As such I am closing this issue. However, including an OMRON-specific format processor argument could be something we incorporate in the future.
